steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['sql', 'export', 'sql', 'inst1lmpb9', 'gs://testingbucketlmpb9/sqldumpfile.gz', '--database=lmpbdata']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-rd', 'gs://testingbucketlmpb9', 'gs://bucketlogslmpb9']  
